### ISSUE TITLE
Taklons don't autodecline charge power with PI in last turn

### ISSUE THREAD

**Issue by coyotte508** [boardgamers/gaia-engine#214]
There is no known scenario when they woudln't want to.

Example: https://gaiaform.io/game/Blunt-stay-5780

**Comment by tysen2k** [comment]
Actually the issue is that they didn't auto accept 1 power.

**Comment by coyotte508** [comment]
Oh that can be explained. They have two choices: charge power first, then gain token, or gain token first, then charge power. 

The game should probably always choose the option to charge power first unless everything is filled then?
