### ISSUE TITLE
needIncomeSelection should be automated

### ISSUE THREAD

**Issue by zeitlinger** [boardgamers/gaia-engine#221]
I'm wondering if needIncomeSelection can be automated.

Intuitively, I'd say yes - is there any counter-example?

**Comment by coyotte508** [comment]
You mean that there is always an optimal choice for the order between adding tokens and charging power?

I don't think so. Imagine you have 0/3/0, and +4pw / +2t.

You can end up with either:

- 2/0/3
- 0/3/2 which is 0/1/3 after burning 1 power

In some cases, 2/0/3 is better, in other, 0/1/3 is better. I don't think it can be automated.

**Comment by AlphaZero86** [comment]
In this example the player would be asked, but in other cases it could become automatic

for example the player has 0/2/0, and +2pw / +2t

he could end up with either

- 0/4/0, which is 0/0/2 after burning 2 power, or
- 2/0/2, which is always better if the player's race is not Itars or Taklons.

**Comment by AlphaZero86** [comment]
if the Player is Itars or Taklons the Player can be asked each time, if he want add or charge Tokens

**Comment by AlphaZero86** [comment]
Also there could be an option for the player, if he wants his income to be automatic or if he wants to get asked each time.
In automatic mode put as many tokens in area 3 as possible unless power charges would be wasted.

**Comment by coyotte508** [comment]
Yes there are cases when it can be automatic, a simple one is when the power is already full.

**Comment by AlphaZero86** [comment]
the Brainstone could become automatic as well if the Player wants to.

**Comment by zeitlinger** [comment]
> the Brainstone could become automatic as well if the Player wants to.

added #226 for this.
