### ISSUE TITLE
Less unnecessary questions for the Player

### ISSUE THREAD

**Issue by AlphaZero86** [boardgamers/gaia-engine#225]
**1st**
For the Itars and Taklons races, the player should only be asked if he wants to charge 1 token when another player is building near him if he has no tokens in area 1. Otherwise it would not cause the player to be able to burn less power, which is the reason why he is asked at all
**2nd**
For the Taklons, the player should only be asked in which area the Brainstone should be, if the player spends his power and the Brainstone is in area 3. Otherwise, it is always better for the player if the brainstone is in the highest possible area.

**Comment by zeitlinger** [comment]
#224 partly addresses this issue.
